# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17.0.1
          registry-url: https://npm.pkg.github.com/
          cache: "npm"
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_PACKAGE_PAT}}
      - run: npm run build --if-present
        env:
          REACT_APP_AIRTABLE_API_KEY: ${{ secrets.REACT_APP_AIRTABLE_API_KEY }}
          REACT_APP_AIRTABLE_BASE_ID: ${{ secrets.REACT_APP_AIRTABLE_BASE_ID }}
          REACT_APP_AIRTABLE_TABLE_ID_WAITING_LIST: ${{ secrets.REACT_APP_AIRTABLE_TABLE_ID_WAITING_LIST }}
      - run: npm run test:cover
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  deploy:
    needs: build-and-test
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - uses: actions/configure-pages@v1
      - uses: actions/upload-pages-artifact@v1
        with:
          path: build
      - id: deployment
        uses: actions/deploy-pages@main
